name: Terraform scan using OpenAI API

on:
  push:
    branches:
      - master

jobs:
  scan-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install openai
          pip install PyGithub
      
      - name: Scan Terraform files using OpenAI
        env:
          xeonproc_pat: ${{ secrets.xeonproc_pat }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 scan_tf.py | tee scan_output.txt

      - name: Print GitHub access token
        run: echo "${{ secrets.xeonproc_pat }}"
        
      - name: Print output to console
        if: always()
        run: cat scan_output.txt
