name: Terraform Compliance Check

on:
  push:
    branches:
      - master

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
    - name: Run compliance check
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python scan_tf.py
