name: Terraform scan using OpenAI API

on:
  push:
    branches:
      - master

jobs:
  scan-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install openai
          pip install PyGithub
      
      - name: Scan Terraform files using OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_PAT: ${{ secrets.GITHUB_PAT }}
        run: |
          python3 scan_tf.py | tee scan_output.txt

      - name: Print output to console
        if: always()
        run: cat scan_output.txt

      - name: Upload output as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: scan-output
          path: scan_output.txt
